from selenium import webdriver
import time
driver=webdriver.Chrome()
driver.get("https://www.baidu.com/")
driver.implicitly_wait(3)
# driver.find_element_by_id("kw") .send_keys("孔雪儿")
# driver.find_element_by_id("su") .click()
# driver.find_element_by_name("wd") .send_keys("大鱼海棠")
# driver.find_element_by_id("su") .click()
#driver.find_element_by_link_text("hao123") .click()
driver.find_element_by_id("kw").send_keys("孔雪儿")
time.sleep(3)
driver.find_element_by_id("kw") .clear()
driver.find_element_by_id("kw") .send_keys("希林娜依高")
driver.find_element_by_id("su").submit()
#driver.maximize_window()
#driver.set_window_size(400,200)
time.sleep(5)
driver.back()
time.sleep(5)
driver.forward()
time.sleep(5)
driver.quit()