from selenium import webdriver
import time
driver=webdriver.Chrome()
driver.get("https://www.baidu.com/")
#driver.implicitly_wait(3)
# driver.find_element_by_id("query").send_keys("虞书欣")
# driver.find_element_by_id("stb").click()
# driver.find_element_by_name("query") .send_keys("赵海棠")
# driver.find_elements_by_id("stb").click()
# driver.find_element_by_tag_name("input") .send_keys("中国")
# driver.find_element_by_tag_name("input") .click()
# driver.find_element_by_class_name("s_ipt").send_keys("虞书欣")
# driver.find_element_by_class_name("bg s_btn").click()
# driver.find_element_by_xpath("//*[@id='kw']") .send_keys("乃万")
# driver.find_element_by_xpath("//*[@id='su']").click()
# driver.find_element_by_link_text("hao123").click()
# driver.implicitly_wait(3)
#driver.maximize_window()
driver.find_element_by_id("kw").send_keys("虞书欣")
driver.find_element_by_id("su").click()
# driver.set_window_size(1000,800)

# print(driver.title)
# print(driver.current_url )
#driver.implicitly_wait(10)
# driver.find_element_by_id("kw").send_keys("赵海棠")
# driver.find_element_by_id("kw") .submit()
#driver.find_element_by_link_text("虞书欣_百度百科").click()
time.sleep(6)
driver.back()
time.sleep(5)
driver.forward()
time.sleep(5)
driver.quit()